FROM node:20-alpine

LABEL org.opencontainers.image.source=https://github.com/qa-tech-training/qadevoprac3-capstone-lab-starter

USER 1000

WORKDIR app

# TODO: add the instructions needed to copy the package.json, install dependencies, and copy the server.js file

COPY package*.json ./

RUN npm install

COPY server.js ./

EXPOSE 3000

CMD ["node", "server.js"]